services:
  mysql:
    image: mysql:8.0
    container_name: mysql-employee-service
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - employee-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  employee-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
